-d C:\Users\ADMIN\Documents\Watchdog_Kiwi1P5_Project\watchdog_project\impl\gwsynthesis\watchdog_project.vg
-p GW1N-1P5C-QFN48X-7
-pn GW1N-UV1P5QN48XC7/I6
-cst C:\Users\ADMIN\Documents\Watchdog_Kiwi1P5_Project\watchdog_project\src\kiwi1p5_pinout.cst
-cfg C:\Users\ADMIN\Documents\Watchdog_Kiwi1P5_Project\watchdog_project\impl\pnr\device.cfg
-sdc C:\Users\ADMIN\Documents\Watchdog_Kiwi1P5_Project\watchdog_project\src\top_watchdog.sdc
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
