`timescale 1ns / 1ps

// =============================================================================
// Module: uart_rx
// Description: UART Receiver module with 16x oversampling and majority voting
//              for robust noise immunity. Fractional baud rate generator.
// =============================================================================

module uart_rx #(
    parameter CLK_FREQ  = 27_000_000, 
    parameter BAUD_RATE = 115200      
)(
    input  wire       clk,
    input  wire       rst_n,
    input  wire       uart_rx_i,      // UART RX serial input pin
    output reg  [7:0] data_o,         // 8-bit received data
    output reg        rx_done_o       // 1-cycle pulse indicating reception complete
);

    // =========================================================
    // FRACTIONAL BAUD GENERATOR (16x Oversampling)
    // =========================================================
    // Phase accumulator for 16x baud oversampling.
    // baud_tick is a 1-cycle pulse generated by the carry-out of the addition.
    localparam [16:0] BAUD_ACC_INC = 17'd4474;
    
    reg  [15:0] baud_acc;
    wire [16:0] baud_sum  = {1'b0, baud_acc} + BAUD_ACC_INC;
    wire        baud_tick = baud_sum[16];
    
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            baud_acc <= 16'd0;
        end else begin
            baud_acc <= baud_sum[15:0];
        end
    end

    // =========================================================
    // FSM STATES
    // =========================================================
    localparam S_IDLE  = 2'b00;
    localparam S_START = 2'b01;
    localparam S_DATA  = 2'b10;
    localparam S_STOP  = 2'b11;

    reg [1:0]  state;
    reg [3:0]  oversample_cnt;  // 0-15 position within bit period
    reg [2:0]  bit_index;
    
    // =========================================================
    // 2-FF SYNCHRONIZER
    // =========================================================
    reg rx_sync1;
    reg rx_sync2;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rx_sync1 <= 1'b1;
            rx_sync2 <= 1'b1;
        end else begin
            rx_sync1 <= uart_rx_i;
            rx_sync2 <= rx_sync1;
        end
    end

    // =========================================================
    // MAJORITY VOTER (3-of-3 sampling at oversample positions 7, 8, 9)
    // =========================================================
    reg [2:0] sample_reg;  // Shift register for 3 consecutive samples
    wire      sampled_bit = (sample_reg[2] & sample_reg[1]) | 
                            (sample_reg[2] & sample_reg[0]) | 
                            (sample_reg[1] & sample_reg[0]);

    // =========================================================
    // RX FSM LOGIC WITH 16x OVERSAMPLING
    // =========================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state          <= S_IDLE;
            oversample_cnt <= 4'd0;
            bit_index      <= 3'd0;
            sample_reg     <= 3'b111;  // Default to idle (high)
            data_o         <= 8'd0;
            rx_done_o      <= 1'b0;
        end else begin
            rx_done_o <= 1'b0;  // Default: only pulse for 1 cycle when done

            case (state)
                S_IDLE: begin
                    oversample_cnt <= 4'd0;
                    bit_index      <= 3'd0;
                    sample_reg     <= 3'b111;
                    
                    // Detect Start bit (falling edge: 1 -> 0)
                    if (rx_sync2 == 1'b0) begin
                        state <= S_START;
                    end
                end
                
                S_START: begin
                    // Wait for the middle of Start bit (oversample positions 7, 8, 9)
                    if (baud_tick) begin
                        oversample_cnt <= oversample_cnt + 4'd1;
                        
                        // Sample at positions 7, 8, 9
                        if (oversample_cnt >= 4'd7 && oversample_cnt <= 4'd9) begin
                            sample_reg <= {sample_reg[1:0], rx_sync2};
                        end
                        
                        // At position 15, decide if Start bit is valid
                        if (oversample_cnt == 4'd15) begin
                            if (sampled_bit == 1'b0) begin
                                // Start bit confirmed
                                state          <= S_DATA;
                                oversample_cnt <= 4'd0;
                                sample_reg     <= 3'b111;
                            end else begin
                                // Glitch detected, return to IDLE
                                state <= S_IDLE;
                            end
                        end
                    end
                end
                
                S_DATA: begin
                    // Receive 8 data bits (LSB first)
                    if (baud_tick) begin
                        oversample_cnt <= oversample_cnt + 4'd1;
                        
                        // Sample at positions 7, 8, 9 of each bit period
                        if (oversample_cnt >= 4'd7 && oversample_cnt <= 4'd9) begin
                            sample_reg <= {sample_reg[1:0], rx_sync2};
                        end
                        
                        // At position 15, store the majority-voted bit
                        if (oversample_cnt == 4'd15) begin
                            data_o[bit_index] <= sampled_bit;
                            
                            if (bit_index < 3'd7) begin
                                bit_index      <= bit_index + 3'd1;
                                oversample_cnt <= 4'd0;
                                sample_reg     <= 3'b111;
                            end else begin
                                // All data bits received, move to Stop bit
                                state          <= S_STOP;
                                oversample_cnt <= 4'd0;
                                sample_reg     <= 3'b111;
                            end
                        end
                    end
                end
                
                S_STOP: begin
                    // Wait for Stop bit (should be high, at least one bit period)
                    if (baud_tick) begin
                        oversample_cnt <= oversample_cnt + 4'd1;
                        
                        // Sample at positions 7, 8, 9 for Stop bit validation
                        if (oversample_cnt >= 4'd7 && oversample_cnt <= 4'd9) begin
                            sample_reg <= {sample_reg[1:0], rx_sync2};
                        end
                        
                        // At position 15, check Stop bit and signal reception complete
                        if (oversample_cnt == 4'd15) begin
                            if (sampled_bit == 1'b1) begin
                                // Stop bit valid
                                rx_done_o <= 1'b1;
                            end
                            // Return to IDLE regardless (error tolerance)
                            state <= S_IDLE;
                        end
                    end
                end
                
                default: state <= S_IDLE;
            endcase
        end
    end

endmodule