`timescale 1ns / 1ps

// =============================================================================
// Module: uart_tx
// Description: UART Transmitter module. Serializes 8-bit data into a bitstream
//              with Start and Stop bits. Configurable baud rate.
// =============================================================================

module uart_tx #(
    parameter CLK_FREQ  = 27_000_000,
    parameter BAUD_RATE = 115200
)(
    input  wire       clk,
    input  wire       rst_n,
    input  wire       tx_start_i,     // 1-cycle pulse to initiate transmission
    input  wire [7:0] data_i,         // 8-bit data to transmit
    output reg        uart_tx_o,      // UART TX serial output pin
    output reg        tx_busy_o,      // High when transmission is in progress
    output reg        tx_done_o       // 1-cycle pulse when byte transmission completes
);

    localparam [16:0] BAUD_ACC_INC = 17'd4474;

    // =========================================================
    // FRACTIONAL BAUD GENERATOR
    // =========================================================
    // Phase accumulator for 16x baud oversampling.
    // baud_tick is a 1-cycle pulse generated by the carry-out of the addition.
    reg  [15:0] baud_acc;
    wire [16:0] baud_sum  = {1'b0, baud_acc} + BAUD_ACC_INC;
    wire        baud_tick = baud_sum[16];
    
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            baud_acc <= 16'd0;
        end else begin
            baud_acc <= baud_sum[15:0];
        end
    end

    // =========================================================
    // FSM STATES
    // =========================================================
    localparam S_IDLE  = 2'b00;
    localparam S_START = 2'b01;
    localparam S_DATA  = 2'b10;
    localparam S_STOP  = 2'b11;

    reg [1:0]  state;
    reg [3:0]  baud_cnt;    // Counter for baud ticks (0-15 for 1 bit period)
    reg [2:0]  bit_index;
    reg [7:0]  data_reg;

    // =========================================================
    // TX FSM LOGIC
    // =========================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state     <= S_IDLE;
            uart_tx_o <= 1'b1;        // TX line is high when idle
            tx_busy_o <= 1'b0;
            tx_done_o <= 1'b0;
            baud_cnt  <= 4'd0;
            bit_index <= 3'd0;
            data_reg  <= 8'd0;
        end else begin
            // Default: tx_done_o is only asserted for 1 cycle when transmission completes
            tx_done_o <= 1'b0;
            
            case (state)
                S_IDLE: begin
                    uart_tx_o <= 1'b1;
                    tx_busy_o <= 1'b0;
                    baud_cnt  <= 4'd0;
                    bit_index <= 3'd0;
                    if (tx_start_i) begin
                        data_reg  <= data_i;
                        tx_busy_o <= 1'b1;
                        state     <= S_START;
                    end
                end

                S_START: begin
                    uart_tx_o <= 1'b0; // Pull TX low for Start bit
                    if (baud_tick) begin
                        if (baud_cnt < 4'd15) begin
                            baud_cnt <= baud_cnt + 4'd1;
                        end else begin
                            baud_cnt <= 4'd0;
                            state    <= S_DATA;
                        end
                    end
                end

                S_DATA: begin
                    uart_tx_o <= data_reg[bit_index]; // Transmit data bit by bit
                    if (baud_tick) begin
                        if (baud_cnt < 4'd15) begin
                            baud_cnt <= baud_cnt + 4'd1;
                        end else begin
                            baud_cnt <= 4'd0;
                            if (bit_index < 3'd7) begin
                                bit_index <= bit_index + 3'd1;
                            end else begin
                                bit_index <= 3'd0;
                                state     <= S_STOP;
                            end
                        end
                    end
                end

                S_STOP: begin
                    uart_tx_o <= 1'b1; // Pull TX high for Stop bit
                    if (baud_tick) begin
                        if (baud_cnt < 4'd15) begin
                            baud_cnt <= baud_cnt + 4'd1;
                        end else begin
                            baud_cnt  <= 4'd0;
                            tx_done_o <= 1'b1;  // Pulse tx_done for 1 cycle
                            state     <= S_IDLE;
                        end
                    end
                end
                
                default: state <= S_IDLE;
            endcase
        end
    end

endmodule